# See docs: https://embarkstudios.github.io/cargo-deny/checks/index.html

[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = [
    # FIXME(#2471):
    # The `failure` crate is officially end-of-life: it has been marked as deprecated
    # by the former maintainer, who has announced that there will be no updates or
    # maintenance work on it going forward.
    # URL: https://github.com/rust-lang-nursery/failure/pull/347
    "RUSTSEC-2020-0036",
    # FIXME(#2472)
    # `stb_truetype` crate has been deprecated; use `ttf-parser` instead
    # This crate was maintained for use in rusttype which has switched to use [ttf-parser](https://crates.io/crates/ttf-parser)
    # URL: https://gitlab.redox-os.org/redox-os/stb_truetype-rs/-/commit/f1f5be4794e87bfc80a4255bc3f23ed75dd77645
    "RUSTSEC-2020-0020",

    # FIXME: net2 is pulled in via `mio` (https://github.com/tokio-rs/mio/issues/1319#issuecomment-683496712)
    # The [`net2`](https://crates.io/crates/net2) crate has been deprecated
    # and users are encouraged to considered [`socket2`](https://crates.io/crates/socket2) instead.
    # URL: https://github.com/deprecrated/net2-rs/commit/3350e3819adf151709047e93f25583a5df681091
    "RUSTSEC-2020-0016",
]

[bans]
multiple-versions = "deny"
wildcards = "deny"
skip = [
    # FIXME: Waiting for gltf to update its base64 dep: https://github.com/gltf-rs/gltf/pull/292
    { version = "=0.11.0", name = "base64" },

    # FIXME: Waiting for alga to update its num-complex dep: https://github.com/dimforge/alga/pull/99
    { version = "=0.2.4", name = "num-complex" },

    # FIXME: Waiting for shred to update its hashbrown dep: https://github.com/amethyst/shred/pull/200
    { version = "=0.7.2", name = "hashbrown" }
]
skip-tree = [
    # FIXME: update and deduplicate all of these crates:

    # There are > 27 crate duplicates pulled in by the old version of rendy we use
    { version = "=0.4.1", name = "rendy", depth = 6 },

    # There are 3 different minor versions of `rand` in the dependency
    # tree that cause a lot of rand_* crates to be duplicated
    { version = "=0.4.6", name = "rand", depth = 2 },
    { version = "=0.6.5", name = "rand", depth = 2 },
]
deny = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[licenses]
unlicensed = "deny"
copyleft = "deny"
default = "deny"
allow-osi-fsf-free = "neither"

deny = []

# Run `cargo deny list` to see which crates use which license
# and add them to this array if we accept them
allow = [
    "MIT",
    "Apache-2.0",
    "Unlicense",
    "Zlib",
    "MPL-2.0",
    "CC0-1.0",
    "ISC",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "FTL",
]

# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93
